---
title: "Prediction Project - Data Prep"
subtitle: "STA 101L - Summer 1 2022"
editor: visual
editor_options: 
  chunk_output_type: console
---

The data can be found [here](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Datasets/DVS/natality/Nat2020us.zip) and the help file [here](https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/DVS/natality/UserGuide2020.pdf)

## Raw Data import

```{r}
knitr::opts_chunk$set(
  eval = FALSE
)
```

```{r}
set.seed(0)
library(tidyverse)

d_raw <- read_csv(
  "../Nat2020us/Nat2020PublicUS.c20210506.r20210812.txt",
  col_names = FALSE, trim_ws = FALSE
  ) %>%
  slice_sample(n = 10e3)

save(d_raw, file = "projects/d_raw.RDATA")
```

## Variable extraction

```{r}
clean_data <- function(data){
  
  data_clean <- data %>%
    rename(string = X1) %>%
    mutate(
      month                            = str_sub(string, 13 , 14 ) %>% as.numeric,
      mother_age                       = str_sub(string, 75 , 76 ) %>% as.numeric,
      prenatal_care_starting_month     = str_sub(string, 224, 225) %>% as.numeric,
      daily_cigarette_prepregnancy     = str_sub(string, 253, 254) %>% as.numeric,
      daily_cigarette_trimester_1      = str_sub(string, 255, 256) %>% as.numeric,
      daily_cigarette_trimester_2      = str_sub(string, 257, 258) %>% as.numeric,
      daily_cigarette_trimester_3      = str_sub(string, 259, 260) %>% as.numeric,
      mother_height                    = str_sub(string, 280, 281) %>% as.numeric,
      mother_bmi                       = str_sub(string, 283, 286) %>% as.numeric,
      mother_weight_prepregnancy       = str_sub(string, 292, 294) %>% as.numeric,
      mother_weight_delivery           = str_sub(string, 299, 301) %>% as.numeric,
      mother_diabetes_prepregnancy     = str_sub(string, 313, 313),
      mother_diabetes_gestational      = str_sub(string, 314, 314),
      mother_hypertension_prepregnancy = str_sub(string, 315, 315),
      mother_hypertension_gestational  = str_sub(string, 316, 316),
      mother_no_risk_factor            = str_sub(string, 337, 337) %>% as.numeric,
      mother_gonorrhea                 = str_sub(string, 343, 343),
      mother_syphilis                  = str_sub(string, 344, 344),
      mother_chlamydia                 = str_sub(string, 345, 345),
      mother_hepatitis_B               = str_sub(string, 346, 346),
      mother_hepatitis_C               = str_sub(string, 347, 347),
      number_newborns                  = str_sub(string, 454, 454) %>% as.numeric,
      newborn_sex                      = str_sub(string, 475, 475),
      gestation_week                   = str_sub(string, 490, 491) %>% as.numeric,
      newborn_birth_weight             = str_sub(string, 504, 507) %>% as.numeric
      ) %>%
    filter(
      gestation_week               <  99  ,
      number_newborns              == 1   ,
      mother_no_risk_factor        <= 1   ,
      mother_weight_delivery       <  999 ,
      mother_weight_prepregnancy   <  999 ,
      mother_bmi                   <  99  ,
      mother_height                <  99  ,
      daily_cigarette_trimester_3  <  98  ,
      daily_cigarette_trimester_2  <  98  ,
      daily_cigarette_trimester_1  <  98  ,
      daily_cigarette_prepregnancy <  98  ,
      prenatal_care_starting_month <  99  ,
      newborn_birth_weight         <  9999,
      mother_diabetes_prepregnancy == "N",
      mother_hypertension_gestational == "N",
      mother_gonorrhea == "N",
      mother_syphilis == "N",
      mother_chlamydia == "N",
      mother_hepatitis_B == "N",
      mother_hepatitis_C == "N"
      ) %>%
  mutate(mother_risk_factor = !mother_no_risk_factor) %>%
    select(
      - string, - number_newborns,
      - mother_diabetes_prepregnancy, - mother_hypertension_gestational, - mother_hypertension_prepregnancy, - mother_gonorrhea, - mother_syphilis, - mother_chlamydia, - mother_hepatitis_B, - mother_hepatitis_C, - mother_no_risk_factor
      ) %>%
    select(
      newborn_birth_weight, everything()
    )
      
  return(data_clean)
  
}
```

```{r}
d_sub_clean <- clean_data(d_sub)

d_train <- slice(d_sub_clean, 1     : 1e3)
d_test  <- slice(d_sub_clean, 1e4+1 : 2e4)

write_csv(d_train, "projects/training_set.csv")
#write_csv(d_test , "projects/test_set.csv"    )
```

## Checking subset

```{r}
d_num <- d_sub_clean %>% select_if(is.numeric)
for(i in 1 : ncol(d_num)){
  hist(d_num[[i]], breaks = 30, xlab = names(d_num)[i], main = i)
}

d_cha <- d_sub_clean %>% select_if(is.character)
for(i in 1 : ncol(d_cha)){
  print(names(d_cha)[i])
  print(table(d_cha[[i]]))
}
```

```{r}
m_simple <- lm(newborn_birth_weight ~ gestation_week, data = d_train)
summary(m_simple)
m_full <- lm(newborn_birth_weight ~ ., data = d_train)
summary(m_full)
y     <- d_test$newborn_birth_weight
RMST <- sqrt(mean((y - mean(y))^2))
y_hat <- predict.lm(m_full, d_test)
sqrt(mean((y - y_hat  )^2))
y_hat <- predict.lm(m_simple, d_test)
sqrt(mean((y - y_hat  )^2))
```
