project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "STA 101L - Summer I 2022"
  description: "Homepage for STA 101L - Data Analysis and Statistical Inference at Duke University, Summer I 2022."
  site-url: "https://sta101L-suI22.github.io/website/"

  repo-url: https://github.com/rmorsomme/website
  repo-actions: [edit, issue]

  # opengraph: true
  # twitter-card:
  #   creator: "@minebocek"
  #   image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Raphael Morsomme"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.jpg"
    pinned: true
    align: center
    # tools:
    #   - icon: person-fill
    #     text: "Gradescope"
    #     url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
        # menu:
        #   - text: Gradescope
        #     url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/page/aec742dc-2972-4f02-a35b-1dd3315af889

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      #- section: "Computing"
      #  contents:
      #    - href: computing-access.qmd
      #      text: Access
      - section: "Project"
        contents:
          # - href: project-description.qmd
          #   text: Description
          # - href: project-tips-resources.qmd
          #   text: Tips + resources
          - href: project-prediction.qmd
            text: Prediction project
          - href: project-inference.qmd
            text: Inference project
      # - section: "Weekly materials"
      #   contents:
      #     - href: weeks/week-1.qmd
      #       text: "Week 1"
      # - section: "Supplemental notes"
      #   contents:
      #     - href: supplemental/slr-derivations.qmd
      #       text: SLR derivations

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual