---
title: "STA 101L: Data Analysis and Statistical Inference"
tbl-colwidths: [5,10,20,5,5,5,5,10]
resources: 
  - "*.Rmd"
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| Week  | Date         | Topic                                          | Reading                    | Slides                                                                   | Lab                                                                                                                                              | HW                  | Project                                                                    |
+:=====:+==============+================================================+:==========================:+:========================================================================:+:================================================================================================================================================:+:===================:+:==========================================================================:+
| 0.5   | Wed, May 11  | Welcome to STA 101!                            | (1.2; 2.2-3)               | [🖥️](/slides/lec-1.html "Lecture slides"){aria-label="Lecture 1 slides"} |                                                                                                                                                  |                     |                                                                            |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Types of data and studies                      |                            | [🖥️](/slides/lec-2.html "Lecture slides"){aria-label="Lecture 2 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, May 12  | Visualization I                                | 5.1-5.6                    | [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, May 13  | Lab 1 - Introduction to R and RStudio          |                            |                                                                          | [💻](https://openintro.shinyapps.io/ims-01-data-01/ "Lab instructions"){aria-label="Lab 1 instructions"}                                         |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Sun, May 15  | Due: homework 1                                |                            |                                                                          |                                                                                                                                                  | [✍️](/hw/hw-1.html) |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 1     | Mon, May 16  | Visualization II                               | 4.1-4.5                    | [🖥️](/slides/lec-3.html "Lecture slides"){aria-label="Lecture 3 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, May 17  | Simple linear regression                       | 7.1-7.3                    | [🖥️](/slides/lec-4.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, May 18  | Lab 2 - Visualization                          |                            |                                                                          | [💻](http://openintrostat.github.io/oilabs-tidy/02_intro_to_data/intro_to_data.html "Lab instructions"){aria-label="Lab 1 instructions"}         | [✍️](/hw/hw-2.html) |                                                                            |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Due: Homework 2                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, May 19  | Multiple linear regression                     | 8.1-8.2                    | [🖥️](/slides/lec-5.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, May 20  | Lab 3 - Linear regression                      |                            |                                                                          | [💻](http://openintrostat.github.io/oilabs-tidy/08_simple_regression/simple_regression.html "Lab instructions"){aria-label="Lab 1 instructions"} |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Sun, May 22  | Due: Homework 3                                |                            |                                                                          |                                                                                                                                                  | [✍️](/hw/hw-3.html) |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 2     | Mon, May 23  | Model selection I                              | 8.3                        | [🖥️](/slides/lec-6.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, May 24  | Model selection II                             | 8.4; 25.3                  | [🖥️](/slides/lec-6.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, May 25  | Lab 4 - functions, loops                       |                            |                                                                          | [💻](/documents/lab-5.pdf "Lab instructions"){aria-label="Lab 1 instructions"}                                                                   |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, May 26  | Logistic regression                            | 9.1-9.3                    | [🖥️](/slides/lec-7.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  | [✍️](/hw/hw-4.html) | [📂](/projects/rmd_tips.Rmd "Tips for rmd"){aria-label="Lecture 4 slides"} |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Work on project                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Due: Homework 4                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, May 27  | Lab 5 - work on prediction project \[PP\]      |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 3     | Mon, May 30  | Memorial Day holiday                           |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, May 31  | Due: PP model                                  | 11.0; 11.3; 12.0; 12.3     | [🖥️](/slides/lec-8.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     | PP model (9:00am)                                                          |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | PP presentations                               |                            |                                                                          |                                                                                                                                                  |                     | PP presentation                                                            |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Principles of inference                        |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, June 1  | Lab 6 - Lecture on inference for proportions I | 16.1-16.2; 17.1-17.3       | [🖥️](/slides/lec-9.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     | PP report                                                                  |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Due: PP report                                 |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, June 2  | Inference for proportions II                   | 13.1-13.3                  | [🖥️](/slides/lec-9.html "Lecture slides"){aria-label="Lecture 4 slides"} |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, June 3  | Lab 7 - Inference for proportions              |                            |                                                                          | [💻](https://openintro.shinyapps.io/ims-05-infer-01/ "Lab instructions"){aria-label="Lab 1 instructions"}                                        |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Sun, June 5  | Due: homework 5                                |                            |                                                                          |                                                                                                                                                  | [✍️](/hw/hw-5.html) |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 4     | Mon, June 6  | Inference for means I                          | 19.1-19.2                  |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, June 7  | Inference for means II                         | 20.1-20.4; 21.1-21.3       |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, June 8  | Lab 8 - Inference for means                    |                            |                                                                          | [💻](https://openintro.shinyapps.io/ims-05-infer-07/ "Lab instructions"){aria-label="Lab 1 instructions"}                                        |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, June 9  | Inference for regression                       | 24.2-24.6; 25.1; 26.1-26.2 |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, June 10 | Lab 9 - inference for regression               |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 5     | Mon, June 13 | ANOVA and $\chi^2$ tests                       | 18.1-18.2; 22.2-22.3       |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, June 14 | Work on inference project (IP)                 |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, June 15 | Lab 10 - work on IP                            |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, June 16 | IP presentations                               |                            |                                                                          |                                                                                                                                                  |                     | IP presentation                                                            |
|       |              |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
|       |              | Wrap up                                        |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Fri, June 17 | Lab 11 - work on IP                            |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
| 6     | Mon, June 20 | Juneteenth holiday                             |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Tue, June 21 | Reading period                                 |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Wed, June 22 |                                                |                            |                                                                          |                                                                                                                                                  |                     |                                                                            |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
|       | Thu, June 23 | Due: IP report                                 |                            |                                                                          |                                                                                                                                                  |                     | IP report                                                                  |
+-------+--------------+------------------------------------------------+----------------------------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+----------------------------------------------------------------------------+
:::

```{r echo = FALSE}
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |
