---
title: "Principles of Inference"
subtitle: "STA 101L - Summer I 2022"
author: "Raphael Morsomme"
footer:  "[https://rmorsomme.github.io/website/](https://rmorsomme.github.io/website/)"
logo: "images/logo.jpg"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: true
    transition: fade
    slide-number: true
    code-fold: false
    code-summary: "Show the code"
    scrollable: true
editor: visual
execute:
  freeze: auto
  echo: true
editor_options: 
  chunk_output_type: console
---

```{r setup}
#| include: false

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%",
  fig.align = "center"
)

# load packages
library(tidyverse)   # for data wrangling and visualization
library(tidymodels)  # for modeling
library(countdown)
library(openintro)

# set default theme and larger font size for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))

options(scipen = 100)
```

# Welcome

## Announcements

-   

## Recap

## Outline

-   Statistical inference
-   Confidence intervals
-   Hypothesis tests
    -   Types of errors
-   Five cases
    -   single proportion

    -   difference between two portions

    -   single mean

    -   difference between two means

    -   regression parameters

# Statistical inference

## Learning about a proportion

example

## Point estimate

**parameter of interest**: proportion in the population

**sample statistic**: sample proportion

It seems natural to use the sample proportion as an estimate for the population proportion.

## Limitation of point estimate

A single point does not indicate how confident we are in our estimation.

-   If we have a *large* sample, then we can be pretty confident that our estimate will likely be close to the true value fo the parameter,

-   if we have a *small* sample, then we know that our estimate may be far from the truth.

-   e.g. basketball free throws, ratings on Yelp or Amazon

## Statistical inference

Framework to make rigorous statements about uncertainty in our estimates

-   confidence intervals

    -   "we are 90% confident that the interval $(20\%, 30\%)$ captures the true value of the population proportion".

-   hypothesis tests

    -   "we reject the claim that the population proportion is $50\%$".

# Five cases

## Case 1 -- Single proportion {.smaller}

What is the proportion of vegetarian among Duke students?

. . .

**Population parameter**: proportion of vegetarian among Duke students ($p$)

**sample statistics**: proportion of vegetarian in the sample $\hat{p}$

. . .

**Confidence interval**: $(0.31, 0.43)$

-   we are 95% confident that the interval $(0.31, 0.43)$ capture the proportion of vegetarian among Duke students.

. . .

**Hypothesis test**: is the proportion of vegetarian among Duke students $0.5$?

-   $H_0:p=0.5, H_a:p\neq0.5$

-   The data collected provide strong evidence against $H_0$, that is, against the hypothesis that half of Duke students are vegetarian.

## Case 2 -- Difference between two proportions {.smaller}

Is the proportion of vegetarian the same among undergraduate Duke student and graduate Duke students?

**Population parameter**: difference between the proportion of vegetarian among undergraduate Duke students and graduate Duke students ($p_{diff} = p_{undergrad}-p_{grad}$)

**sample statistics**: different in proportion of vegetarian in the sample $\hat{p}_{diff} = \hat{p}_{undergrad} - \hat{p}_{grad}$

. . .

**Confidence interval**: $(-0.05, 0.08)$

-   we are 95% confident that the interval $(-0.05, 0.08)$ capture the true value of $p_{diff}$.

. . .

**Hypothesis test**: is the proportion of vegetarian the same among undergraduate and graduate Duke students?

-   $H_0:p_{diff}=0, H_a:p_{diff}\neq0$

-   The data collected do not provide strong evidence against $H_0$, that is, against the hypothesis that $p_{diff}=0$.

## Case 3 -- Single mean

How much time do Duke students sleep on average per night?

. . .

**Population parameter**: mean amount of time that Duke students sleep per night ($\mu$)

**sample statistics**: average amount of time that Duke students in the sample sleep per night ($\bar{x}$)

. . .

**Confidence interval**: $(5.5, 7.5)$

-   we are 95% confident that the interval $(5.5, 7.5)$ capture $\mu$.

. . .

**Hypothesis test**: is the proportion of vegetarian among Duke students $0.5$?

-   $H_0:\mu=8, H_a:\mu\neq8$

-   The data collected provide strong evidence against $H_0$, that is, against the hypothesis that Duke students sleep on average 8 hours per night.

## Case 4 -- Difference between two proportions

Do undergraduate Duke students sleep the same mount of time per night as graduate Duke students do?

. . .

**Population parameter**: difference between the mean amount of time that Duke undergraduate and graduate students sleep per night ($\mu_{diff} = \mu_{undergrad}-\mu_{grad}$)

**sample statistics**: difference between the mean amount of time that Duke undergraduate and graduate students in the sample sleep per night ($\bar{x}_{diff} = \bar{x}_{undergrad} - \bar{x}_{grad}$)

. . .

**Confidence interval**: $(-0.5, 1)$

-   we are 95% confident that the interval $(-0.5, 1)$ capture $\mu_{diff}$.

. . .

**Hypothesis test**: is the proportion of vegetarian among Duke students $0.5$?

-   $H_0:\mu_{diff}=0, H_a:\mu_{diff}\neq0$

-   The data collected do not provide strong evidence against $H_0$, that is, against the hypothesis that undergraduate and graduate Duke students sleep on average the amount of time per night.
