---
title: ""
subtitle: ""
author: "Raphael Morsomme"
footer:  "[https://rmorsomme.github.io/website/](https://rmorsomme.github.io/website/)"
logo: "images/logo.jpg"
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
    code-fold: false
    code-summary: "Show the code"
    scrollable: true
    link-external-newwindow: true
    history: false
editor: visual
execute:
  freeze: auto
  echo: true
editor_options: 
  chunk_output_type: console
---

```{r setup}
#| include: false

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = 0.618,
  fig.retina = 3,
  dpi = 300,
  out.width = "80%",
  fig.align = "center"
)

# load packages
library(tidyverse)   # for data wrangling and visualization
library(tidymodels)  # for modeling
library(countdown)
library(openintro)

# set default theme and larger font size for ggplot2
ggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))

options(scipen = 100)
```

Here are the teams for the prediction project.

```{r, results='hold'}
  set.seed(5) # set the seed for the random number generator
  teams <- sample(
    c("Hayden", "Janice", "Kennedy", "Maggie", "Melissa", "Yuanzhi"), # elements from which to choose
    size = 6 # number of items to choose
    )
  print(paste0("Team 1: ", teams[1], " and ", teams[2]))
  print(paste0("Team 2: ", teams[3], " and ", teams[4]))
  print(paste0("Team 3: ", teams[5], " and ", teams[6]))
```
