---
title: "HW 2 - Data visualization and summary"
subtitle: "Due Wednesday, May 18, 9:00pm on Gradescope"
---

This assignment needs to be completed with RMarkdown and submitted as a PDF on [Gradescope](https://www.gradescope.com/courses/394638). Feel free to re-use the template provided for HW1.

When submitting your work on Gradescope, please assign a page for each question.

## Problem set (25 points)

-   Exercise 5.2 (2 points)
-   Exercise 5.4 (2 points) -- instead of drawing, you may describe the relationship in words.
-   Exercise 5.6 (3 points)
-   Exercise 5.10 (3 points)
-   Exercise 5.16 (5 points)
-   Exercise 5.20 (1 points)
-   Exercise 5.20 follow up (1 points)
    -   Would side-by-side boxplots have been suitable to visualize these data? Briefly explain.
-   Exercise 5.22 (2 points)
-   Exercise 5.26 (2 points)
-   Exercise 4.6 (4 points)

\newpage

## Lab exercises - New York flights (25 points)

You can find the lab [here](http://openintrostat.github.io/oilabs-tidy/02_intro_to_data/intro_to_data.html)

-   Exercise 1 (2 points)
-   Exercise 2 (3 points)
-   Exercise 3 (3 points)
-   Exercise 4 (3 points)
-   Exercise 5 (2 points)
-   Exercise 6 (2 points)
-   Exercise 7 (2 points)
-   Exercise 8 (3 points)
-   Exercise 9 (5 points)
