---
title: "HW 6 - Inference for means"
subtitle: "Due Wednesday, June 8, 9:00pm on Gradescope"
---

This assignment needs to be completed with RMarkdown and submitted as a PDF on [Gradescope](https://www.gradescope.com/courses/394638). Feel free to re-use the template provided for HW1.

When submitting your work on Gradescope, please assign a page for each question.

## Problem set (25 points)

-   19.2 (2 points)
-   19.6 (2 points) -- part b only
-   19.20 (2.5 points)
-   20.4 (2 points)
-   20.6 (1 point) -- part a only
-   20.8 (6 points)
-   21.2 (2 points)
-   21.4 (1.5 points)
-   21.6 (2.5 points)
-   21.8 (1.5 points) -- skip part b; in part c, only interpret CI from part a
-   21.10 (2 points)

## Lab exercises - the Youth Risk Behavior Surveillance System (25 points)

You can find the lab [here](http://openintrostat.github.io/oilabs-tidy/07_inf_for_numerical_data/inf_for_numerical_data.html).

-   Exercise 1 (2 points)
-   Exercise 2 (1 point)
-   Exercise 3 (2 points) -- see the [ggplot2 cheatsheet](https://rmorsomme.github.io/website/course-links.html) for the command to make violin plot.
-   Exercise 4 (1 point)
-   Exercise 5 (1 point)
-   Exercise 6 (2 points)
-   Exercise 7 (1 point)
-   Exercise 8 (1 point)
-   Exercise 9 (2 points)
-   Exercise 10 (2 points)
-   Exercise 11 (2 points)
-   Exercise 12 (2 points)
-   Exercise 13 (2 points)
-   Exercise 14 (4 points)
